version: '3.8'

services:
  conductor-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conductor-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:-please-change-this-secret-in-production}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-conductor2024}
      - INVITE_CODE=${INVITE_CODE:-conductor2024}
      - DB_PATH=/app/data/conductor.db
    volumes:
      # Persist database and logs
      - conductor_data:/app/data
      - conductor_logs:/app/logs
      # Optional: mount local env file
      # - ./.env:/app/.env:ro
    networks:
      - conductor-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for HTTPS
  conductor-proxy:
    image: nginx:alpine
    container_name: conductor-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./ssl:/etc/nginx/ssl:ro  # For HTTPS certificates
    depends_on:
      - conductor-server
    networks:
      - conductor-network
    profiles:
      - proxy

volumes:
  conductor_data:
    driver: local
  conductor_logs:
    driver: local

networks:
  conductor-network:
    driver: bridge