name: conductor_client
description: Conductor flash mob organization mobile client

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.2
  
  # State management
  provider: ^6.0.5
  
  # Network and HTTP
  http: ^0.13.5
  dio: ^5.3.2
  
  # Local storage
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.0
  
  # QR code scanning
  qr_code_scanner: ^1.0.1
  
  # Connectivity
  connectivity_plus: ^4.0.2
  
  # UI and utilities
  intl: ^0.18.1
  path_provider: ^2.1.1
  crypto: ^3.0.3
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Conductor
      fonts:
        - asset: assets/fonts/Conductor-Regular.ttf
        - asset: assets/fonts/Conductor-Bold.ttf
          weight: 700